# Generated by Django 3.0.7 on 2020-06-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200619_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('id',)},
        ),
    ]
