# Generated by Django 3.0.7 on 2020-06-20 17:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200620_1450'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('AccountManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
